### ISSUE TITLE
remove with group identifier

### ISSUE THREAD

**Issue by hzandi** [nicephoton/NiceNotifications#1]
Hi there 
How remove a group with a group identifier? 
#feature

**Comment by dreymonde** [comment]
Hi @hzandi! if you can't use your existing notification group type, you can create a "mock" one

```swift
final class GroupForRemoval: LocalNotificationsGroup {
    let groupIdentifier: String = "yourIdentifierHere"

    func getTimeline(completion: @escaping (NotificationsTimeline) -> ()) {
        // no-act
    }
}
```

and then use that. It's not pretty or elegant but it'll work, since the notification removal logic only looks on the identifier
